### ISSUE TITLE
怎么监听视图弹开与关闭？

### ISSUE THREAD

**Issue by yushan023** [MengLiMing/MLMOptionSelectView#2]
![be54ce74-9450-4a1f-8f2b-6902f8b46345](https://cloud.githubusercontent.com/assets/20593532/23652475/13932c50-0364-11e7-9f6a-0818ca22af89.png)
下拉列表出现的时候想通知按钮的三角形翻转与文字变成红色，
下拉列表消失的时候想通知按钮的三角形回复原样与文字变成黑色。

**Comment by MengLiMing** [comment]
你可以添加两个block，分别放在show方法和dismiss方法的地方

**Comment by MengLiMing** [comment]
但是我感觉如果你只是想实现把三角形翻转是不需要知道列表时展开还是消失吧。利用button的selected就可以实现了
